############################################################################
#                _____           _                                         #
#               / ____|         | |                                        #
#              | |        ___   | |   ___    _ __   ___                    #
#              | |       / _ \  | |  / _ \  | '__| / __|                   #
#              | |____  | (_) | | | | (_) | | |    \__ \                   #
#               \_____|  \___/  |_|  \___/  |_|    |___/                   #
#                                                                          #
# ColorCodes: https://minecraft.gamepedia.com/Formatting_codes#Color_codes #
#                                                                          #
############################################################################
#
#English: Used for very important things.
#German/Deutsch: Wird bei sehr wichtigen Sachen verwendet.
Primary='b'
#
#English: Used for Inventory names and Item names.
#German/Deutsch: Wird bei Inventar-Namen und Item-Namen verwendet.
Secondary='3'
#
#English: Is used for important things (specially in texts).
#German/Deutsch: Wird bei wichtigen Sachen (vor allem in Texten) verwendet.
Important='8'
#
#English: Used in texts.
#German/Deutsch: Wird bei Texten verwendet.
Text='7'
#
#English: for prefixes
#German/Deutsch: für Prefixe
Extra='l'
#
#English: for designs
#German/Deutsch: für Designs
Design='m'
